
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

public class ButtonMasherV2 extends TickTockFrame {

    int score = 0;
    int addScore = 1;
    int ComputerScore = 0;
    int differenceScores = 0;
    int clicks = 0;
//    int BestScore = 0;
    int time = 0;
    int computerInterval = 0;
    
    //Store Variables
    boolean boughtClick1 = false;
    boolean boughtClick2 = false;
    boolean boughtClick3 = false;
    boolean boughtClick4 = false;
    boolean boughtClick5 = false;
    boolean boughtClick6 = false;
    boolean boughtClick7 = false;
    boolean boughtClick8 = false;
    boolean boughtClick9 = false;
    boolean battleCPU = false;
    
    public ButtonMasherV2() {
        initComponents();
        hitButton.setEnabled(false);
        clicksBox.setText("" + clicks);
        clicksBox.setEditable(false);
        timerBox.setEditable(false);
        textTalk.setEditable(false);
        computerScore.setEditable(false);
        scoreBox.setEditable(false);
        textTalk.setText("Welcome to Button MasherV2!");
        buyClick1.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        buttonMasherTab = new javax.swing.JLayeredPane();
        goButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        timerBox = new javax.swing.JTextField();
        textTalk = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        scoreBox = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        computerScore = new javax.swing.JTextField();
        hitButton = new javax.swing.JButton();
        slotMachine = new javax.swing.JLayeredPane();
        spinButton = new javax.swing.JButton();
        slotTalk = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        picture1 = new javax.swing.JLabel();
        picture3 = new javax.swing.JLabel();
        picture2 = new javax.swing.JLabel();
        storeTab = new javax.swing.JLayeredPane();
        jLabel4 = new javax.swing.JLabel();
        clicksBox = new javax.swing.JTextField();
        buyClick1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        buyClick2 = new javax.swing.JButton();
        buyClick3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        buyCPUBattle = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        buyClick4 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        buyClick5 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        buyClick6 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        buyClick7 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        buyClick8 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        buyClick9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(790, 630));
        setResizable(false);

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(790, 630));
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        buttonMasherTab.setPreferredSize(new java.awt.Dimension(790, 600));

        goButton.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        goButton.setText("Go!");
        goButton.setPreferredSize(new java.awt.Dimension(220, 200));
        goButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setText("Timer");
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 100));

        timerBox.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        timerBox.setPreferredSize(new java.awt.Dimension(200, 100));
        timerBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timerBoxActionPerformed(evt);
            }
        });

        textTalk.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        textTalk.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel2.setText("Score");
        jLabel2.setPreferredSize(new java.awt.Dimension(220, 100));

        scoreBox.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        scoreBox.setPreferredSize(new java.awt.Dimension(220, 100));
        scoreBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scoreBoxActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel3.setText("CPU Score");
        jLabel3.setPreferredSize(new java.awt.Dimension(220, 100));

        computerScore.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        computerScore.setPreferredSize(new java.awt.Dimension(220, 100));
        computerScore.setRequestFocusEnabled(false);
        computerScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computerScoreActionPerformed(evt);
            }
        });

        hitButton.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        hitButton.setText("Hit Button");
        hitButton.setPreferredSize(new java.awt.Dimension(300, 80));
        hitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitButtonActionPerformed(evt);
            }
        });

        buttonMasherTab.setLayer(goButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        buttonMasherTab.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        buttonMasherTab.setLayer(timerBox, javax.swing.JLayeredPane.DEFAULT_LAYER);
        buttonMasherTab.setLayer(textTalk, javax.swing.JLayeredPane.DEFAULT_LAYER);
        buttonMasherTab.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        buttonMasherTab.setLayer(scoreBox, javax.swing.JLayeredPane.DEFAULT_LAYER);
        buttonMasherTab.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        buttonMasherTab.setLayer(computerScore, javax.swing.JLayeredPane.DEFAULT_LAYER);
        buttonMasherTab.setLayer(hitButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout buttonMasherTabLayout = new javax.swing.GroupLayout(buttonMasherTab);
        buttonMasherTab.setLayout(buttonMasherTabLayout);
        buttonMasherTabLayout.setHorizontalGroup(
            buttonMasherTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonMasherTabLayout.createSequentialGroup()
                .addGroup(buttonMasherTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(buttonMasherTabLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(buttonMasherTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonMasherTabLayout.createSequentialGroup()
                                .addComponent(scoreBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(computerScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(buttonMasherTabLayout.createSequentialGroup()
                                .addGroup(buttonMasherTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(goButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9)
                                .addGroup(buttonMasherTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(timerBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(9, 9, 9)
                        .addComponent(hitButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(buttonMasherTabLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(textTalk, javax.swing.GroupLayout.PREFERRED_SIZE, 758, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        buttonMasherTabLayout.setVerticalGroup(
            buttonMasherTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonMasherTabLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(buttonMasherTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(buttonMasherTabLayout.createSequentialGroup()
                        .addGroup(buttonMasherTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(buttonMasherTabLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(timerBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(goButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(buttonMasherTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(buttonMasherTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scoreBox, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(computerScore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(hitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(textTalk, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jTabbedPane1.addTab("Button Masher", buttonMasherTab);

        spinButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        spinButton.setText("Spin!");

        slotTalk.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        slotTalk.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        slotTalk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slotTalkActionPerformed(evt);
            }
        });

        jPanel1.setPreferredSize(new java.awt.Dimension(441, 36));

        picture1.setText("jLabel25");
        picture1.setPreferredSize(new java.awt.Dimension(146, 14));

        picture3.setText("jLabel25");
        picture3.setPreferredSize(new java.awt.Dimension(146, 14));

        picture2.setText("jLabel25");
        picture2.setPreferredSize(new java.awt.Dimension(146, 14));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(picture1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(picture3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(picture2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(picture1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(picture2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(picture3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        slotMachine.setLayer(spinButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        slotMachine.setLayer(slotTalk, javax.swing.JLayeredPane.DEFAULT_LAYER);
        slotMachine.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout slotMachineLayout = new javax.swing.GroupLayout(slotMachine);
        slotMachine.setLayout(slotMachineLayout);
        slotMachineLayout.setHorizontalGroup(
            slotMachineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slotMachineLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(slotMachineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(slotTalk)
                    .addGroup(slotMachineLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spinButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        slotMachineLayout.setVerticalGroup(
            slotMachineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, slotMachineLayout.createSequentialGroup()
                .addComponent(slotTalk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(slotMachineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spinButton, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Slot Machine", slotMachine);

        storeTab.setPreferredSize(new java.awt.Dimension(175, 35));
        storeTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                storeTabMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setText("Clicks");
        jLabel4.setPreferredSize(new java.awt.Dimension(200, 60));

        clicksBox.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        clicksBox.setPreferredSize(new java.awt.Dimension(200, 100));

        buyClick1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        buyClick1.setText("Buy");
        buyClick1.setEnabled(false);
        buyClick1.setPreferredSize(new java.awt.Dimension(175, 65));
        buyClick1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyClick1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel5.setText("+1/Click");
        jLabel5.setPreferredSize(new java.awt.Dimension(175, 60));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel6.setText("Cost: 300 Clicks");
        jLabel6.setPreferredSize(new java.awt.Dimension(175, 35));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel7.setText("+2/Click");
        jLabel7.setPreferredSize(new java.awt.Dimension(175, 60));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel8.setText("Cost: 450 Clicks");
        jLabel8.setPreferredSize(new java.awt.Dimension(175, 35));

        buyClick2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        buyClick2.setText("Buy");
        buyClick2.setEnabled(false);
        buyClick2.setPreferredSize(new java.awt.Dimension(175, 65));
        buyClick2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyClick2ActionPerformed(evt);
            }
        });

        buyClick3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        buyClick3.setText("Buy");
        buyClick3.setEnabled(false);
        buyClick3.setPreferredSize(new java.awt.Dimension(175, 65));
        buyClick3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyClick3ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel9.setText("Cost: 600 Clicks");
        jLabel9.setPreferredSize(new java.awt.Dimension(175, 35));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel10.setText("+3/Click");
        jLabel10.setPreferredSize(new java.awt.Dimension(175, 60));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel11.setText("CPU of Doom");
        jLabel11.setToolTipText("");
        jLabel11.setPreferredSize(new java.awt.Dimension(175, 60));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setText("Cost: 920 Clicks");
        jLabel13.setPreferredSize(new java.awt.Dimension(175, 35));

        buyCPUBattle.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        buyCPUBattle.setText("Buy");
        buyCPUBattle.setEnabled(false);
        buyCPUBattle.setPreferredSize(new java.awt.Dimension(146, 37));
        buyCPUBattle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyCPUBattleActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel12.setText("+4/Click");
        jLabel12.setToolTipText("");
        jLabel12.setPreferredSize(new java.awt.Dimension(175, 60));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel14.setText("Cost: 750 Clicks");
        jLabel14.setPreferredSize(new java.awt.Dimension(175, 35));

        buyClick4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        buyClick4.setText("Buy");
        buyClick4.setEnabled(false);
        buyClick4.setPreferredSize(new java.awt.Dimension(175, 65));
        buyClick4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyClick4ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel15.setText("+5/Click");
        jLabel15.setToolTipText("");
        jLabel15.setPreferredSize(new java.awt.Dimension(175, 60));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel16.setText("Cost: 900 Clicks");
        jLabel16.setPreferredSize(new java.awt.Dimension(175, 35));

        buyClick5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        buyClick5.setText("Buy");
        buyClick5.setEnabled(false);
        buyClick5.setPreferredSize(new java.awt.Dimension(175, 65));
        buyClick5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyClick5ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel17.setText("+6/Click");
        jLabel17.setToolTipText("");
        jLabel17.setPreferredSize(new java.awt.Dimension(175, 60));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel18.setText("Cost: 1050 Clicks");
        jLabel18.setPreferredSize(new java.awt.Dimension(175, 35));

        buyClick6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        buyClick6.setText("Buy");
        buyClick6.setEnabled(false);
        buyClick6.setPreferredSize(new java.awt.Dimension(175, 65));
        buyClick6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyClick6ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel19.setText("+7/Click");
        jLabel19.setPreferredSize(new java.awt.Dimension(175, 60));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel20.setText("Cost: 1200 Clicks");
        jLabel20.setPreferredSize(new java.awt.Dimension(175, 35));

        buyClick7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        buyClick7.setText("Buy");
        buyClick7.setEnabled(false);
        buyClick7.setPreferredSize(new java.awt.Dimension(175, 65));
        buyClick7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyClick7ActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel21.setText("+8/Click");
        jLabel21.setPreferredSize(new java.awt.Dimension(175, 60));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel22.setText("Cost: 1350 Clicks");
        jLabel22.setPreferredSize(new java.awt.Dimension(175, 35));

        buyClick8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        buyClick8.setText("Buy");
        buyClick8.setEnabled(false);
        buyClick8.setPreferredSize(new java.awt.Dimension(175, 65));
        buyClick8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyClick8ActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel23.setText("+9/Click");
        jLabel23.setPreferredSize(new java.awt.Dimension(175, 60));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel24.setText("Cost: 1500 Clicks");
        jLabel24.setPreferredSize(new java.awt.Dimension(175, 35));

        buyClick9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        buyClick9.setText("Buy");
        buyClick9.setEnabled(false);
        buyClick9.setPreferredSize(new java.awt.Dimension(175, 65));
        buyClick9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyClick9ActionPerformed(evt);
            }
        });

        storeTab.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        storeTab.setLayer(clicksBox, javax.swing.JLayeredPane.DEFAULT_LAYER);
        storeTab.setLayer(buyClick1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        storeTab.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        storeTab.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        storeTab.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        storeTab.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        storeTab.setLayer(buyClick2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        storeTab.setLayer(buyClick3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        storeTab.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        storeTab.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        storeTab.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        storeTab.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        storeTab.setLayer(buyCPUBattle, javax.swing.JLayeredPane.DEFAULT_LAYER);
        storeTab.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        storeTab.setLayer(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        storeTab.setLayer(buyClick4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        storeTab.setLayer(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        storeTab.setLayer(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        storeTab.setLayer(buyClick5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        storeTab.setLayer(jLabel17, javax.swing.JLayeredPane.DEFAULT_LAYER);
        storeTab.setLayer(jLabel18, javax.swing.JLayeredPane.DEFAULT_LAYER);
        storeTab.setLayer(buyClick6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        storeTab.setLayer(jLabel19, javax.swing.JLayeredPane.DEFAULT_LAYER);
        storeTab.setLayer(jLabel20, javax.swing.JLayeredPane.DEFAULT_LAYER);
        storeTab.setLayer(buyClick7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        storeTab.setLayer(jLabel21, javax.swing.JLayeredPane.DEFAULT_LAYER);
        storeTab.setLayer(jLabel22, javax.swing.JLayeredPane.DEFAULT_LAYER);
        storeTab.setLayer(buyClick8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        storeTab.setLayer(jLabel23, javax.swing.JLayeredPane.DEFAULT_LAYER);
        storeTab.setLayer(jLabel24, javax.swing.JLayeredPane.DEFAULT_LAYER);
        storeTab.setLayer(buyClick9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout storeTabLayout = new javax.swing.GroupLayout(storeTab);
        storeTab.setLayout(storeTabLayout);
        storeTabLayout.setHorizontalGroup(
            storeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(storeTabLayout.createSequentialGroup()
                .addGroup(storeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(storeTabLayout.createSequentialGroup()
                        .addGroup(storeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(storeTabLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(storeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(storeTabLayout.createSequentialGroup()
                                        .addGroup(storeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(clicksBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(10, 10, 10))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, storeTabLayout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, storeTabLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(buyCPUBattle, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(storeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(storeTabLayout.createSequentialGroup()
                                .addGroup(storeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(storeTabLayout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(10, 10, 10)
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(storeTabLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(storeTabLayout.createSequentialGroup()
                                .addComponent(buyClick1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buyClick2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buyClick3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(storeTabLayout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(storeTabLayout.createSequentialGroup()
                                .addGroup(storeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(storeTabLayout.createSequentialGroup()
                                        .addGroup(storeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(buyClick4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(storeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(buyClick5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buyClick8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(storeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buyClick9, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(storeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(buyClick6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                        .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(storeTabLayout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(buyClick7, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        storeTabLayout.setVerticalGroup(
            storeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(storeTabLayout.createSequentialGroup()
                .addGroup(storeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(storeTabLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(storeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(storeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buyClick1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buyClick2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buyClick3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, storeTabLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(storeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(storeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clicksBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(storeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(storeTabLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buyCPUBattle, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(storeTabLayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buyClick4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(storeTabLayout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buyClick5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(storeTabLayout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buyClick6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(storeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(storeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(storeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buyClick8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buyClick7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buyClick9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Store", storeTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitButtonActionPerformed
        score = score + addScore;
        scoreBox.setText("" + score);
    }//GEN-LAST:event_hitButtonActionPerformed

    private void computerScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computerScoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_computerScoreActionPerformed

    private void scoreBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scoreBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scoreBoxActionPerformed

    private void timerBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timerBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timerBoxActionPerformed

    private void goButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goButtonActionPerformed
        score = 0;
        ComputerScore = 0;
        scoreBox.setText("" + score);
        computerScore.setText("" + ComputerScore);   
        goButton.setEnabled(false);
        time = 15;
        computerInterval = (int)(Math.random()*200)+1;
//        int start = 3;
       
        if (battleCPU == true){
            computerInterval = 1;
            battleCPU = false;
        }
        
//        while (start > 0){
//           textTalk.setText("" + start);
//            start = start - 1;
//            delay(1000);
//        }
        
        textTalk.setText("GO!");
        timerBox.setText("" + time);
        setInterval1(1000);
        setInterval2(computerInterval);
        startTimer1();
        startTimer2();
    }//GEN-LAST:event_goButtonActionPerformed

    private void buyClick1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyClick1ActionPerformed
        addScore = 2;
        clicks = clicks - 30;
        boughtClick1 = true;
        clicksBox.setText("" + clicks);
        buyClick1.setText("Bought!");
        buyClick1.setEnabled(false);
        
        // Allowing you to buy other click perks
        boughtClick2 = false;
        boughtClick3 = false;
        boughtClick4 = false;
        boughtClick5 = false;
        boughtClick6 = false;
        boughtClick7 = false;
        boughtClick8 = false;
        boughtClick9 = false;
    }//GEN-LAST:event_buyClick1ActionPerformed

    private void storeTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_storeTabMouseClicked
        
    }//GEN-LAST:event_storeTabMouseClicked

    private void buyClick2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyClick2ActionPerformed
        addScore = 3;
        clicks = clicks - 45;
        boughtClick2 = true;
        clicksBox.setText("" + clicks);
        buyClick2.setText("Bought!");
        buyClick2.setEnabled(false);
        
        // Allowing you to buy other click perks
        boughtClick1 = false;
        boughtClick3 = false;
        boughtClick4 = false;
        boughtClick5 = false;
        boughtClick6 = false;
        boughtClick7 = false;
        boughtClick8 = false;
        boughtClick9 = false;
    }//GEN-LAST:event_buyClick2ActionPerformed

    private void buyClick3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyClick3ActionPerformed
        addScore = 4;
        clicks = clicks - 60;
        boughtClick3 = true;
        clicksBox.setText("" + clicks);
        buyClick3.setText("Bought!");
        buyClick3.setEnabled(false);
        
        // Allowing you to buy other click perks
        boughtClick1 = false;
        boughtClick2 = false;
        boughtClick4 = false;
        boughtClick5 = false;
        boughtClick6 = false;
        boughtClick7 = false;
        boughtClick8 = false;
        boughtClick9 = false;
    }//GEN-LAST:event_buyClick3ActionPerformed

    private void buyCPUBattleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyCPUBattleActionPerformed
        battleCPU = true;
        clicks = clicks - 920;
        clicksBox.setText("" + clicks);
        buyCPUBattle.setText("Bought!");
        buyCPUBattle.setEnabled(false);
    }//GEN-LAST:event_buyCPUBattleActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        clicksBox.setText("" + clicks);
        
        if (clicks >=300 && boughtClick1 == false){
            buyClick1.setText("Buy");
            buyClick1.setEnabled(true);
        }
        
        if (clicks >=450 && boughtClick2 == false){
            buyClick2.setText("Buy");
            buyClick2.setEnabled(true);
        }
        
        if (clicks >=600 && boughtClick3 == false){
            buyClick3.setText("Buy");
            buyClick3.setEnabled(true);
        }
        
        if (clicks >=750 && boughtClick4 == false){
            buyClick4.setText("Buy");
            buyClick4.setEnabled(true);
        }
        
        if (clicks >=900 && boughtClick5 == false){
            buyClick5.setText("Buy");
            buyClick5.setEnabled(true);
        }
        
        if (clicks >=1050 && boughtClick6 == false){
            buyClick6.setText("Buy");
            buyClick6.setEnabled(true);
        }
        
        if (clicks >=1200 && boughtClick7 == false){
            buyClick7.setText("Buy");
            buyClick7.setEnabled(true);
        }
        
        if (clicks >=1350 && boughtClick8 == false){
            buyClick8.setText("Buy");
            buyClick8.setEnabled(true);
        }
        
        if (clicks >=1500 && boughtClick9 == false){
            buyClick9.setText("Buy");
            buyClick9.setEnabled(true);
        }
        
        if (clicks >=920 && battleCPU == false){
            buyCPUBattle.setText("Buy");
            buyCPUBattle.setEnabled(true);
        }
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void buyClick4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyClick4ActionPerformed
        addScore = 5;
        clicks = clicks - 75;
        boughtClick4 = true;
        clicksBox.setText("" + clicks);
        buyClick4.setText("Bought!");
        buyClick4.setEnabled(false);
        
        // Allowing you to buy other click perks
        boughtClick1 = false;
        boughtClick2 = false;
        boughtClick3 = false;
        boughtClick5 = false;
        boughtClick6 = false;
        boughtClick7 = false;
        boughtClick8 = false;
        boughtClick9 = false;
    }//GEN-LAST:event_buyClick4ActionPerformed

    private void buyClick5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyClick5ActionPerformed
        addScore = 6;
        clicks = clicks - 90;
        boughtClick5 = true;
        clicksBox.setText("" + clicks);
        buyClick5.setText("Bought!");
        buyClick5.setEnabled(false);
        
        // Allowing you to buy other click perks
        boughtClick1 = false;
        boughtClick2 = false;
        boughtClick3 = false;
        boughtClick4 = false;
        boughtClick6 = false;
        boughtClick7 = false;
        boughtClick8 = false;
        boughtClick9 = false;
    }//GEN-LAST:event_buyClick5ActionPerformed

    private void buyClick6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyClick6ActionPerformed
        addScore = 7;
        clicks = clicks - 105;
        boughtClick6 = true;
        clicksBox.setText("" + clicks);
        buyClick6.setText("Bought!");
        buyClick6.setEnabled(false);
        
        // Allowing you to buy other click perks
        boughtClick1 = false;
        boughtClick2 = false;
        boughtClick3 = false;
        boughtClick4 = false;
        boughtClick5 = false;
        boughtClick7 = false;
        boughtClick8 = false;
        boughtClick9 = false;
    }//GEN-LAST:event_buyClick6ActionPerformed

    private void buyClick7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyClick7ActionPerformed
        addScore = 8;
        clicks = clicks - 120;
        boughtClick7 = true;
        clicksBox.setText("" + clicks);
        buyClick7.setText("Bought!");
        buyClick7.setEnabled(false);
        
        // Allowing you to buy other click perks
        boughtClick1 = false;
        boughtClick2 = false;
        boughtClick3 = false;
        boughtClick4 = false;
        boughtClick5 = false;
        boughtClick6 = false;
        boughtClick8 = false;
        boughtClick9 = false;
    }//GEN-LAST:event_buyClick7ActionPerformed

    private void buyClick8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyClick8ActionPerformed
        addScore = 9;
        clicks = clicks - 135;
        boughtClick8 = true;
        clicksBox.setText("" + clicks);
        buyClick8.setText("Bought!");
        buyClick8.setEnabled(false);
        
        // Allowing you to buy other click perks
        boughtClick1 = false;
        boughtClick2 = false;
        boughtClick3 = false;
        boughtClick4 = false;
        boughtClick5 = false;
        boughtClick6 = false;
        boughtClick7 = false;
        boughtClick9 = false;
    }//GEN-LAST:event_buyClick8ActionPerformed

    private void buyClick9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyClick9ActionPerformed
        addScore = 10;
        clicks = clicks - 150;
        boughtClick9 = true;
        clicksBox.setText("" + clicks);
        buyClick9.setText("Bought!");
        buyClick9.setEnabled(false);
        
        // Allowing you to buy other click perks
        boughtClick1 = false;
        boughtClick2 = false;
        boughtClick3 = false;
        boughtClick4 = false;
        boughtClick5 = false;
        boughtClick6 = false;
        boughtClick7 = false;
        boughtClick8 = false;
    }//GEN-LAST:event_buyClick9ActionPerformed

    private void slotTalkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slotTalkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_slotTalkActionPerformed

    public void tick1(){
        hitButton.setEnabled(true);
        textTalk.setText("The computer is clicking at a speed of: " + computerInterval + "ms");
        time = time - 1;
        timerBox.setText("" + time);   
        
        if (time == 0){
            hitButton.setEnabled(false);
            stopTimer1();
            stopTimer2();
            
            if (clicks <= 0 && ComputerScore > score){
                clicks = 0;
            }
            
            else {
                clicks = clicks + (score - ComputerScore);
            }
            
            if (score > ComputerScore){
                differenceScores = score - ComputerScore;
                textTalk.setText("You have outclicked the computer by " + differenceScores + " clicks!");
            }
            
            else if (score < ComputerScore) {
                differenceScores = ComputerScore - score;
                textTalk.setText("The computer has outclicked you by " + differenceScores + " clicks!");
            }
            
            else {
                textTalk.setText("You and the Computer has tied!");
            }
            
            goButton.setEnabled(true); 
        }
    }
    
    public void tick2(){
        ComputerScore = ComputerScore + 1;
        computerScore.setText("" + ComputerScore);
    }
    
    public void delay(long time) {
        try {
            Thread.sleep(time);
        }catch(Exception e) {
            System.out.println("Error delaying");
        }
    }
    
//    public void changeIcon(javax.swing.JLabel picture1, javax.swing.ImageIcon){
//        try {  
//               picture1.setIcon( new ImageIcon(ImageIO.read( new File(imageName) ) ) );
//           } catch(Exception e) {
//               System.out.println("Image loading error!");
//           }
//    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ButtonMasherV2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ButtonMasherV2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ButtonMasherV2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ButtonMasherV2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ButtonMasherV2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane buttonMasherTab;
    private javax.swing.JButton buyCPUBattle;
    private javax.swing.JButton buyClick1;
    private javax.swing.JButton buyClick2;
    private javax.swing.JButton buyClick3;
    private javax.swing.JButton buyClick4;
    private javax.swing.JButton buyClick5;
    private javax.swing.JButton buyClick6;
    private javax.swing.JButton buyClick7;
    private javax.swing.JButton buyClick8;
    private javax.swing.JButton buyClick9;
    private javax.swing.JTextField clicksBox;
    private javax.swing.JTextField computerScore;
    private javax.swing.JButton goButton;
    private javax.swing.JButton hitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel picture1;
    private javax.swing.JLabel picture2;
    private javax.swing.JLabel picture3;
    private javax.swing.JTextField scoreBox;
    private javax.swing.JLayeredPane slotMachine;
    private javax.swing.JTextField slotTalk;
    private javax.swing.JButton spinButton;
    private javax.swing.JLayeredPane storeTab;
    private javax.swing.JTextField textTalk;
    private javax.swing.JTextField timerBox;
    // End of variables declaration//GEN-END:variables
}
